version: '2.1'

volumes:
  db:

services:
  db:
    image: nott_db_dev
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile_db
    env_file:
      - config.env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 10s
      retries: 3
  # A hack to make app wait for db
  db_proxy_dep:
    image: busybox
    depends_on:
      db:
        condition: service_healthy
  backend:
    image: nott_app_dev
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile_app_dev
    environment:
      - SERVER_MODE=development
    env_file:
      - config.env
    command: python3 /srv/manage.py runserver 0.0.0.0:8000
    tty: true
    volumes:
      - ./project:/srv
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db_proxy_dep
  frontend:
    image: tetafro/webpack:8
    command: webpack -w
    volumes:
      - ./project/public/js:/app
