version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Install deps
          command: |
            apk add --quiet --no-progress --no-cache py-pip ansible git
            pip install --quiet docker-compose coverage
      - run:
          name: Create dummy config
          command: cp ./config.env.example ./config.env
      - run:
          name: Set current version in dockerfile
          command: |
            tag=$(git describe --tags $(git rev-list --tags --max-count=1))
            build=$CIRCLE_BUILD_NUM
            sed -i "s/TAG=v0.0.0/TAG=$tag/" deploy/docker/Dockerfile_app_prod
            sed -i "s/BUILD=0/BUILD=$build/" deploy/docker/Dockerfile_app_prod
      - run:
          name: Build application Docker image
          command: docker-compose -f docker-compose-prod.yml build
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose-prod.yml run \
                --rm \
                --entrypoint=python3 \
                app \
                /srv/smart_manage.py test
      - run:
          name: Push Docker images to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push tetafro/nott_web:latest
            docker push tetafro/nott_db:latest
            docker push tetafro/nott_app:latest
      - run:
          name: Deploy
          command: |
            cd deploy/ansible &&
            ansible-playbook \
                --inventory="$SERVER_DNS:$SERVER_SSH_PORT," \
                --extra-vars "domain=$SERVER_DNS user=$REMOTE_USER" \
                server-update.yml
