version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Check docker version
          command: docker version
      - run:
          name: Install pip
          command: apk add --quiet --no-cache py-pip
      - run:
          name: Install docker-compose
          command: pip install --quiet docker-compose
      - run:
          name: Build application Docker image
          command: docker-compose -f ./docker-compose-prod.yml build
      - run:
          name: Check images
          command: docker images
