version: 2
jobs:
  build:
    docker:
      - image: tetafro/webpack:8
    steps:
      - checkout
      - run:
          name: Install NPM dependencies
          command: npm install
          pwd: project/public/js
