version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Build application Docker image
          command: docker build -t tetafro/nott-backend-python .
      - run:
          name: Run tests
          command: |
            docker network create nott
            # Run database
            docker run -d \
              --network nott \
              --env "POSTGRES_USER=postgres" \
              --env "POSTGRES_PASSWORD=postgres" \
              --env "POSTGRES_DB=nott" \
              --name postgres \
              postgres:10
            # Run test in app container
            docker run \
              --network nott \
              --env ALLOWED_HOSTS='*' \
              --env DEBUG=true \
              --env DJANGO_SECRET_KEY=qwerty \
              --env POSTGRES_DB=nott \
              --env POSTGRES_HOST=postgres \
              --env POSTGRES_PASSWORD=postgres \
              --env POSTGRES_PORT=5432 \
              --env POSTGRES_USER=postgres \
              --name nott-backend \
              tetafro/nott-backend-python:latest \
              /app/smart_manage.py test
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push tetafro/nott-backend-python:latest
