version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nott
    steps:
      - checkout
      - run:
          name: Get project dependencies
          command: |
            sudo apt update -y
            sudo apt install -y gcc libpq-dev musl-dev
            sudo pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . .env.example
            ./project/smart_manage.py test
      - run:
          name: Install linters
          command: sudo pip install flake8
      - run:
          name: Run linters
          command: flake8 ./project
  publish:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t tetafro/nott-backend-python .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push tetafro/nott-backend-python:latest
workflows:
  version: 2
  main:
    jobs:
      - test
      - publish:
          requires:
            - test
          context: dockerhub
