version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.10.0-ce
      - run:
          name: Install deps
          command: |
            apk add --quiet --no-progress --no-cache py-pip ansible
            pip install --quiet docker-compose
      # TODO: Decide what to do with secrets
      - run:
          name: Create dummy config
          command: touch config.env
      - run:
          name: Build application Docker image
          command: docker-compose -f docker-compose-prod.yml build
      - run:
          name: Check images
          command: docker images
      - run:
          name: Push Docker images to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push tetafro/nott_web
            docker push tetafro/nott_db
            docker push tetafro/nott_app
      - run:
          name: Deploy
          command: |
            cd deploy/ansible &&
            ansible-playbook --extra-vars "domain=$DOMAIN" --inventory="$DOMAIN" server-update.yml
