- name: Stop and remove all containers
  command: docker-compose down
  args:
    chdir: "/home/{{ user }}/"

- name: Remove project volume
  command: docker volume rm -f nott_project
  args:
    chdir: "/home/{{ user }}/"

- name: Upload docker-compose config
  copy:
    src: "../../docker-compose-prod.yml"
    dest: "/home/{{ user }}/docker-compose.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Get last version of docker images
  command: docker-compose pull
  args:
    chdir: "/home/{{ user }}/"

- name: Apply DB migrations
  command: docker-compose run --rm app python3 /srv/manage.py migrate
  args:
    chdir: "/home/{{ user }}/"

- name: Start service
  command: docker-compose up -d
  args:
    chdir: "/home/{{ user }}/"
